//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sebduruz_GameOfLife.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LangEN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LangEN() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("sebduruz_GameOfLife.Resources.LangEN", typeof(LangEN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actions.
        /// </summary>
        internal static string actionsGroupBox {
            get {
                return ResourceManager.GetString("actionsGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Activate borders.
        /// </summary>
        internal static string activeBordersCheckBox {
            get {
                return ResourceManager.GetString("activeBordersCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cells color.
        /// </summary>
        internal static string cellColorLabel {
            get {
                return ResourceManager.GetString("cellColorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cells Size.
        /// </summary>
        internal static string cellSizeLabel {
            get {
                return ResourceManager.GetString("cellSizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Validate.
        /// </summary>
        internal static string cellSizeValidationButton {
            get {
                return ResourceManager.GetString("cellSizeValidationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The grid will be reset, do you really want to do this action ?.
        /// </summary>
        internal static string confirmationBoxLabel {
            get {
                return ResourceManager.GetString("confirmationBoxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Message.
        /// </summary>
        internal static string confirmationBoxTitle {
            get {
                return ResourceManager.GetString("confirmationBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exportation failed cause of file cannot be readed. Please retry.
        /// </summary>
        internal static string errorExportation {
            get {
                return ResourceManager.GetString("errorExportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The file cannot be readed. Please retry.
        /// </summary>
        internal static string errorFileCannotBeRead {
            get {
                return ResourceManager.GetString("errorFileCannotBeRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cycles done : .
        /// </summary>
        internal static string executedCyclesLabel {
            get {
                return ResourceManager.GetString("executedCyclesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File.
        /// </summary>
        internal static string fileMenuStrip {
            get {
                return ResourceManager.GetString("fileMenuStrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export.
        /// </summary>
        internal static string fileMenuStripExport {
            get {
                return ResourceManager.GetString("fileMenuStripExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Import.
        /// </summary>
        internal static string fileMenuStripImport {
            get {
                return ResourceManager.GetString("fileMenuStripImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Informations.
        /// </summary>
        internal static string informationsGroupBox {
            get {
                return ResourceManager.GetString("informationsGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Last cycles.
        /// </summary>
        internal static string lastCycleButton {
            get {
                return ResourceManager.GetString("lastCycleButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Living Cells : .
        /// </summary>
        internal static string livingCellsLabel {
            get {
                return ResourceManager.GetString("livingCellsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The grid is loading ....
        /// </summary>
        internal static string loadingLabel {
            get {
                return ResourceManager.GetString("loadingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Maximum : .
        /// </summary>
        internal static string maxLivingCellsLabel {
            get {
                return ResourceManager.GetString("maxLivingCellsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Minimum : .
        /// </summary>
        internal static string minLivingCellsLabel {
            get {
                return ResourceManager.GetString("minLivingCellsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Next cycle.
        /// </summary>
        internal static string nextCycleButton {
            get {
                return ResourceManager.GetString("nextCycleButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reset.
        /// </summary>
        internal static string resetButton {
            get {
                return ResourceManager.GetString("resetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rules.
        /// </summary>
        internal static string rulesGroupBox {
            get {
                return ResourceManager.GetString("rulesGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        internal static string settingsGroupBox {
            get {
                return ResourceManager.GetString("settingsGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Speed : .
        /// </summary>
        internal static string speedLabel {
            get {
                return ResourceManager.GetString("speedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start / Break.
        /// </summary>
        internal static string startBreakButton {
            get {
                return ResourceManager.GetString("startBreakButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Statistics.
        /// </summary>
        internal static string statisticsGroupBox {
            get {
                return ResourceManager.GetString("statisticsGroupBox", resourceCulture);
            }
        }
    }
}
